In [3]:
import pandas as pd
import numpy as np

In [4]:
pip install geopy

Requirement already satisfied: geopy in c:\users\fatima\anaconda3\envs\dev\lib\site-packages (2.4.0)
Requirement already satisfied: geographiclib<3,>=1.52 in c:\users\fatima\anaconda3\envs\dev\lib\site-packages (from geopy) (2.0)
Note: you may need to restart the kernel to use updated packages.

In [5]:
import geopy

Import data sets from June 2023 to September 2023

In [6]:
june = "Resourse/JC-202306-citibike-tripdata.csv"
july = "Resourse/JC-202307-citibike-tripdata.csv"
aug = "Resourse/JC-202308-citibike-tripdata.csv"
sept = "Resourse/JC-202309-citibike-tripdata.csv"

In [7]:
june_data = pd.read_csv(june)
july_data = pd.read_csv(july)
aug_data = pd.read_csv(aug)
sept_data = pd.read_csv(sept)

In [8]:
lables=['June','July','August','September']
frames=[june_data,july_data,aug_data,sept_data]
for x in range(4):
    temp=[]
    for i in range(len(frames[x])):
        temp.append(lables[x])
        
    (frames[x])['Month'] = temp

In [9]:
june_df = pd.DataFrame(june_data)
july_df = pd.DataFrame(july_data)
aug_df = pd.DataFrame(aug_data)
sept_df = pd.DataFrame(sept_data)

In [10]:
data_summer2023 = pd.concat([june_df,july_df,aug_df,sept_df],ignore_index=True)

In [11]:
data_summer2023

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual,Month
0,37BE5FCB1A385CDA,classic_bike,2023-06-27 16:06:27,2023-06-27 16:10:27,Hilltop,JC019,Christ Hospital,JC034,40.731115,-74.057468,40.734786,-74.050444,casual,June
1,9C96B4C6CBBB31AD,classic_bike,2023-06-24 10:46:58,2023-06-24 10:55:27,Baldwin at Montgomery,JC020,Hamilton Park,JC009,40.723473,-74.064338,40.727596,-74.044247,member,June
2,C91293605D4BEC07,electric_bike,2023-06-04 20:30:13,2023-06-04 20:34:31,Hilltop,JC019,Brunswick St,JC023,40.731169,-74.057574,40.724176,-74.050656,member,June
3,2920063442116A46,classic_bike,2023-06-08 19:10:06,2023-06-08 19:13:05,Baldwin at Montgomery,JC020,Astor Place,JC077,40.723499,-74.064335,40.719282,-74.071262,member,June
4,E205FD8C18BA263A,classic_bike,2023-06-23 18:53:51,2023-06-23 19:17:50,Baldwin at Montgomery,JC020,Adams St & 11 St,HB507,40.723511,-74.064277,40.750916,-74.033541,member,June
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
409886,A2112D905D1B5FB9,electric_bike,2023-09-05 18:31:42,2023-09-05 18:35:31,8 St & Washington St,HB603,14 St Ferry - 14 St & Shipyard Ln,HB202,40.745984,-74.028199,40.752961,-74.024353,member,September
409887,2C9D64FF1B8C44C8,classic_bike,2023-09-25 08:36:13,2023-09-25 08:39:13,8 St & Washington St,HB603,14 St Ferry - 14 St & Shipyard Ln,HB202,40.744306,-74.034534,40.752961,-74.024353,member,September
409888,4F4E24251BBAB45E,classic_bike,2023-09-19 07:55:23,2023-09-19 07:59:00,8 St & Washington St,HB603,14 St Ferry - 14 St & Shipyard Ln,HB202,40.745984,-74.028199,40.752961,-74.024353,member,September
409889,BB6F0D74150403AC,classic_bike,2023-09-14 07:50:23,2023-09-14 07:52:59,11 St & Washington St,HB502,14 St Ferry - 14 St & Shipyard Ln,HB202,40.749985,-74.027150,40.752961,-74.024353,member,September
409890,755AE0D4205C0306,classic_bike,2023-09-22 06:52:07,2023-09-22 06:55:49,8 St & Washington St,HB603,14 St Ferry - 14 St & Shipyard Ln,HB202,40.745984,-74.028199,40.752961,-74.024353,member,September

# Duration Time
we need to calculate the duration time for each ride from both column start at and end at

In [16]:
data_summer2023.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 409891 entries, 0 to 409890
Data columns (total 14 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   ride_id             409891 non-null  object
 1   rideable_type       409891 non-null  object
 2   started_at          409891 non-null  object
 3   ended_at            409891 non-null  object
 4   start_station_name  409827 non-null  object
 5   start_station_id    409827 non-null  object
 6   end_station_name    408458 non-null  object
 7   end_station_id      408458 non-null  object
 8   start_lat           409891 non-null  float64
 9   start_lng           409891 non-null  float64
 10  end_lat             409459 non-null  float64
 11  end_lng             409459 non-null  float64
 12  member_casual       409891 non-null  object
 13  Month               409891 non-null  object
dtypes: float64(4), object(10)
memory usage: 43.8+ MB

In [30]:
data_summer2023.dtypes

ride_id                       object
rideable_type                 object
started_at                    object
ended_at                      object
start_station_name            object
start_station_id              object
end_station_name              object
end_station_id                object
start_lat                    float64
start_lng                    float64
end_lat                      float64
end_lng                      float64
member_casual                 object
Month                         object
ended_at              datetime64[ns]
dtype: object

In [28]:
data_summer2023['ended_at '] = data_summer2023['ended_at'].apply(pd.to_datetime)

In [29]:
data_summer2023['end_lat'].dtypes

dtype('float64')

In [34]:
data_summer2023 = data_summer2023.astype({'started_at': 'datetime64', 'ended_at': 'datetime64' })

In [35]:
data_summer2023.dtypes

ride_id                       object
rideable_type                 object
started_at            datetime64[ns]
ended_at              datetime64[ns]
start_station_name            object
start_station_id              object
end_station_name              object
end_station_id                object
start_lat                    float64
start_lng                    float64
end_lat                      float64
end_lng                      float64
member_casual                 object
Month                         object
ended_at              datetime64[ns]
dtype: object

In [36]:
Bikedata_summer2023 = data_summer2023.iloc[:,:-1]

In [38]:
Bikedata_summer2023.dtypes

ride_id                       object
rideable_type                 object
started_at            datetime64[ns]
ended_at              datetime64[ns]
start_station_name            object
start_station_id              object
end_station_name              object
end_station_id                object
start_lat                    float64
start_lng                    float64
end_lat                      float64
end_lng                      float64
member_casual                 object
Month                         object
dtype: object

In [41]:
from datetime import datetime

In [45]:
Bikedata_summer2023['started_time'] = Bikedata_summer2023['started_at'].dt.time

In [47]:
Bikedata_summer2023['ended_time'] = Bikedata_summer2023['ended_at'].dt.time

In [49]:
Bikedata_summer2023.dtypes

ride_id                       object
rideable_type                 object
started_at            datetime64[ns]
ended_at              datetime64[ns]
start_station_name            object
start_station_id              object
end_station_name              object
end_station_id                object
start_lat                    float64
start_lng                    float64
end_lat                      float64
end_lng                      float64
member_casual                 object
Month                         object
started_time                  object
ended_time                    object
dtype: object

In [66]:
Bikedata_summer2023 = Bikedata_summer2023.astype({'started_at': 'object', 'ended_at': 'object' })

In [67]:
Bikedata_summer2023.dtypes

ride_id                object
rideable_type          object
started_at             object
ended_at               object
start_station_name     object
start_station_id       object
end_station_name       object
end_station_id         object
start_lat             float64
start_lng             float64
end_lat               float64
end_lng               float64
member_casual          object
Month                  object
started_time           object
ended_time             object
dtype: object

In [97]:
from datetime import datetime

In [100]:
Bikedata_summer2023['ride_duration'] = Bikedata_summer2023.apply(lambda row: (datetime.combine(datetime.min, row['ended_time']) - datetime.combine(datetime.min, row['started_time'])), axis=1)

In [108]:
Bikedata_summer2023 = Bikedata_summer2023.astype({'ride_duration': 'string'})

In [109]:
Bikedata_summer2023['ride_duration'] = Bikedata_summer2023['ride_duration'].str.split(' ').str[-1]

In [110]:
Bikedata_summer2023

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual,Month,started_time,ended_time,ride_duration
0,37BE5FCB1A385CDA,classic_bike,2023-06-27 16:06:27,2023-06-27 16:10:27,Hilltop,JC019,Christ Hospital,JC034,40.731115,-74.057468,40.734786,-74.050444,casual,June,16:06:27,16:10:27,00:04:00
1,9C96B4C6CBBB31AD,classic_bike,2023-06-24 10:46:58,2023-06-24 10:55:27,Baldwin at Montgomery,JC020,Hamilton Park,JC009,40.723473,-74.064338,40.727596,-74.044247,member,June,10:46:58,10:55:27,00:08:29
2,C91293605D4BEC07,electric_bike,2023-06-04 20:30:13,2023-06-04 20:34:31,Hilltop,JC019,Brunswick St,JC023,40.731169,-74.057574,40.724176,-74.050656,member,June,20:30:13,20:34:31,00:04:18
3,2920063442116A46,classic_bike,2023-06-08 19:10:06,2023-06-08 19:13:05,Baldwin at Montgomery,JC020,Astor Place,JC077,40.723499,-74.064335,40.719282,-74.071262,member,June,19:10:06,19:13:05,00:02:59
4,E205FD8C18BA263A,classic_bike,2023-06-23 18:53:51,2023-06-23 19:17:50,Baldwin at Montgomery,JC020,Adams St & 11 St,HB507,40.723511,-74.064277,40.750916,-74.033541,member,June,18:53:51,19:17:50,00:23:59
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
409886,A2112D905D1B5FB9,electric_bike,2023-09-05 18:31:42,2023-09-05 18:35:31,8 St & Washington St,HB603,14 St Ferry - 14 St & Shipyard Ln,HB202,40.745984,-74.028199,40.752961,-74.024353,member,September,18:31:42,18:35:31,00:03:49
409887,2C9D64FF1B8C44C8,classic_bike,2023-09-25 08:36:13,2023-09-25 08:39:13,8 St & Washington St,HB603,14 St Ferry - 14 St & Shipyard Ln,HB202,40.744306,-74.034534,40.752961,-74.024353,member,September,08:36:13,08:39:13,00:03:00
409888,4F4E24251BBAB45E,classic_bike,2023-09-19 07:55:23,2023-09-19 07:59:00,8 St & Washington St,HB603,14 St Ferry - 14 St & Shipyard Ln,HB202,40.745984,-74.028199,40.752961,-74.024353,member,September,07:55:23,07:59:00,00:03:37
409889,BB6F0D74150403AC,classic_bike,2023-09-14 07:50:23,2023-09-14 07:52:59,11 St & Washington St,HB502,14 St Ferry - 14 St & Shipyard Ln,HB202,40.749985,-74.027150,40.752961,-74.024353,member,September,07:50:23,07:52:59,00:02:36
409890,755AE0D4205C0306,classic_bike,2023-09-22 06:52:07,2023-09-22 06:55:49,8 St & Washington St,HB603,14 St Ferry - 14 St & Shipyard Ln,HB202,40.745984,-74.028199,40.752961,-74.024353,member,September,06:52:07,06:55:49,00:03:42

In [111]:
Bikedata_summer2023.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 409891 entries, 0 to 409890
Data columns (total 17 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   ride_id             409891 non-null  object
 1   rideable_type       409891 non-null  object
 2   started_at          409891 non-null  object
 3   ended_at            409891 non-null  object
 4   start_station_name  409827 non-null  object
 5   start_station_id    409827 non-null  object
 6   end_station_name    408458 non-null  object
 7   end_station_id      408458 non-null  object
 8   start_lat           409891 non-null  float64
 9   start_lng           409891 non-null  float64
 10  end_lat             409459 non-null  float64
 11  end_lng             409459 non-null  float64
 12  member_casual       409891 non-null  object
 13  Month               409891 non-null  object
 14  started_time        409891 non-null  object
 15  ended_time          409891 non-null  object
 16  ride_duration       409891 non-null  object
dtypes: float64(4), object(13)
memory usage: 53.2+ MB

In [129]:
Bikedata_summer2023.dropna(subset=['start_lat', 'start_lng', 'end_lat', 'end_lng'], inplace=True)

In [130]:
Bikedata_summer2023["distance"] = ''

In [131]:
import geopy.distance
from geopy.distance import geodesic

for index, row in Bikedata_summer2023.iterrows():
    coords_1 = (row['start_lat'], row['start_lng'])
    coords_2 = (row['end_lat'], row['end_lng'])
    distance_km = geopy.distance.geodesic(coords_1, coords_2).km
    Bikedata_summer2023.at[index, 'distance'] = distance_km

In [132]:
Bikedata_summer2023

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual,Month,started_time,ended_time,ride_duration,distance
0,37BE5FCB1A385CDA,classic_bike,2023-06-27 16:06:27,2023-06-27 16:10:27,Hilltop,JC019,Christ Hospital,JC034,40.731115,-74.057468,40.734786,-74.050444,casual,June,16:06:27,16:10:27,00:04:00,0.719926
1,9C96B4C6CBBB31AD,classic_bike,2023-06-24 10:46:58,2023-06-24 10:55:27,Baldwin at Montgomery,JC020,Hamilton Park,JC009,40.723473,-74.064338,40.727596,-74.044247,member,June,10:46:58,10:55:27,00:08:29,1.758023
2,C91293605D4BEC07,electric_bike,2023-06-04 20:30:13,2023-06-04 20:34:31,Hilltop,JC019,Brunswick St,JC023,40.731169,-74.057574,40.724176,-74.050656,member,June,20:30:13,20:34:31,00:04:18,0.97182
3,2920063442116A46,classic_bike,2023-06-08 19:10:06,2023-06-08 19:13:05,Baldwin at Montgomery,JC020,Astor Place,JC077,40.723499,-74.064335,40.719282,-74.071262,member,June,19:10:06,19:13:05,00:02:59,0.749528
4,E205FD8C18BA263A,classic_bike,2023-06-23 18:53:51,2023-06-23 19:17:50,Baldwin at Montgomery,JC020,Adams St & 11 St,HB507,40.723511,-74.064277,40.750916,-74.033541,member,June,18:53:51,19:17:50,00:23:59,4.000179
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
409886,A2112D905D1B5FB9,electric_bike,2023-09-05 18:31:42,2023-09-05 18:35:31,8 St & Washington St,HB603,14 St Ferry - 14 St & Shipyard Ln,HB202,40.745984,-74.028199,40.752961,-74.024353,member,September,18:31:42,18:35:31,00:03:49,0.840101
409887,2C9D64FF1B8C44C8,classic_bike,2023-09-25 08:36:13,2023-09-25 08:39:13,8 St & Washington St,HB603,14 St Ferry - 14 St & Shipyard Ln,HB202,40.744306,-74.034534,40.752961,-74.024353,member,September,08:36:13,08:39:13,00:03:00,1.289567
409888,4F4E24251BBAB45E,classic_bike,2023-09-19 07:55:23,2023-09-19 07:59:00,8 St & Washington St,HB603,14 St Ferry - 14 St & Shipyard Ln,HB202,40.745984,-74.028199,40.752961,-74.024353,member,September,07:55:23,07:59:00,00:03:37,0.840101
409889,BB6F0D74150403AC,classic_bike,2023-09-14 07:50:23,2023-09-14 07:52:59,11 St & Washington St,HB502,14 St Ferry - 14 St & Shipyard Ln,HB202,40.749985,-74.027150,40.752961,-74.024353,member,September,07:50:23,07:52:59,00:02:36,0.406219
409890,755AE0D4205C0306,classic_bike,2023-09-22 06:52:07,2023-09-22 06:55:49,8 St & Washington St,HB603,14 St Ferry - 14 St & Shipyard Ln,HB202,40.745984,-74.028199,40.752961,-74.024353,member,September,06:52:07,06:55:49,00:03:42,0.840101

In [134]:
Bikedata_summer2023.dtypes

ride_id                object
rideable_type          object
started_at             object
ended_at               object
start_station_name     object
start_station_id       object
end_station_name       object
end_station_id         object
start_lat             float64
start_lng             float64
end_lat               float64
end_lng               float64
member_casual          object
Month                  object
started_time           object
ended_time             object
ride_duration          object
distance               object
dtype: object

In [135]:
# Define a custom function to convert the time duration to minutes
def time_to_minutes(time_str):
    time_parts = time_str.split(':')
    hours, minutes, seconds = map(int, time_parts)
    total_minutes = hours * 60 + minutes + seconds / 60
    return total_minutes

# Apply the custom function to the DataFrame column and store the result as a new column
Bikedata_summer2023['ride_duration_minutes'] = Bikedata_summer2023['ride_duration'].apply(time_to_minutes)

In [136]:
Bikedata_summer2023

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual,Month,started_time,ended_time,ride_duration,distance,ride_duration_minutes
0,37BE5FCB1A385CDA,classic_bike,2023-06-27 16:06:27,2023-06-27 16:10:27,Hilltop,JC019,Christ Hospital,JC034,40.731115,-74.057468,40.734786,-74.050444,casual,June,16:06:27,16:10:27,00:04:00,0.719926,4.000000
1,9C96B4C6CBBB31AD,classic_bike,2023-06-24 10:46:58,2023-06-24 10:55:27,Baldwin at Montgomery,JC020,Hamilton Park,JC009,40.723473,-74.064338,40.727596,-74.044247,member,June,10:46:58,10:55:27,00:08:29,1.758023,8.483333
2,C91293605D4BEC07,electric_bike,2023-06-04 20:30:13,2023-06-04 20:34:31,Hilltop,JC019,Brunswick St,JC023,40.731169,-74.057574,40.724176,-74.050656,member,June,20:30:13,20:34:31,00:04:18,0.97182,4.300000
3,2920063442116A46,classic_bike,2023-06-08 19:10:06,2023-06-08 19:13:05,Baldwin at Montgomery,JC020,Astor Place,JC077,40.723499,-74.064335,40.719282,-74.071262,member,June,19:10:06,19:13:05,00:02:59,0.749528,2.983333
4,E205FD8C18BA263A,classic_bike,2023-06-23 18:53:51,2023-06-23 19:17:50,Baldwin at Montgomery,JC020,Adams St & 11 St,HB507,40.723511,-74.064277,40.750916,-74.033541,member,June,18:53:51,19:17:50,00:23:59,4.000179,23.983333
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
409886,A2112D905D1B5FB9,electric_bike,2023-09-05 18:31:42,2023-09-05 18:35:31,8 St & Washington St,HB603,14 St Ferry - 14 St & Shipyard Ln,HB202,40.745984,-74.028199,40.752961,-74.024353,member,September,18:31:42,18:35:31,00:03:49,0.840101,3.816667
409887,2C9D64FF1B8C44C8,classic_bike,2023-09-25 08:36:13,2023-09-25 08:39:13,8 St & Washington St,HB603,14 St Ferry - 14 St & Shipyard Ln,HB202,40.744306,-74.034534,40.752961,-74.024353,member,September,08:36:13,08:39:13,00:03:00,1.289567,3.000000
409888,4F4E24251BBAB45E,classic_bike,2023-09-19 07:55:23,2023-09-19 07:59:00,8 St & Washington St,HB603,14 St Ferry - 14 St & Shipyard Ln,HB202,40.745984,-74.028199,40.752961,-74.024353,member,September,07:55:23,07:59:00,00:03:37,0.840101,3.616667
409889,BB6F0D74150403AC,classic_bike,2023-09-14 07:50:23,2023-09-14 07:52:59,11 St & Washington St,HB502,14 St Ferry - 14 St & Shipyard Ln,HB202,40.749985,-74.027150,40.752961,-74.024353,member,September,07:50:23,07:52:59,00:02:36,0.406219,2.600000
409890,755AE0D4205C0306,classic_bike,2023-09-22 06:52:07,2023-09-22 06:55:49,8 St & Washington St,HB603,14 St Ferry - 14 St & Shipyard Ln,HB202,40.745984,-74.028199,40.752961,-74.024353,member,September,06:52:07,06:55:49,00:03:42,0.840101,3.700000

In [148]:
Bikedata_summer2023.dtypes

ride_id                   object
rideable_type             object
started_at                object
ended_at                  object
start_station_name        object
start_station_id          object
end_station_name          object
end_station_id            object
start_lat                float64
start_lng                float64
end_lat                  float64
end_lng                  float64
member_casual             object
Month                     object
started_time              object
ended_time                object
ride_duration             object
distance                  object
ride_duration_minutes    float64
dtype: object

In [146]:
Bikedata_summer2023 = Bikedata_summer2023.astype({'ride_duration': 'string'})
Bikedata_summer2023['ride_duration'] = Bikedata_summer2023['ride_duration'].str.split(' ').str[-1]

In [147]:
Bikedata_summer2023

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual,Month,started_time,ended_time,ride_duration,distance,ride_duration_minutes
0,37BE5FCB1A385CDA,classic_bike,2023-06-27 16:06:27,2023-06-27 16:10:27,Hilltop,JC019,Christ Hospital,JC034,40.731115,-74.057468,40.734786,-74.050444,casual,June,16:06:27,16:10:27,00:04:00,0.719926,4.000000
1,9C96B4C6CBBB31AD,classic_bike,2023-06-24 10:46:58,2023-06-24 10:55:27,Baldwin at Montgomery,JC020,Hamilton Park,JC009,40.723473,-74.064338,40.727596,-74.044247,member,June,10:46:58,10:55:27,00:08:29,1.758023,8.483333
2,C91293605D4BEC07,electric_bike,2023-06-04 20:30:13,2023-06-04 20:34:31,Hilltop,JC019,Brunswick St,JC023,40.731169,-74.057574,40.724176,-74.050656,member,June,20:30:13,20:34:31,00:04:18,0.97182,4.300000
3,2920063442116A46,classic_bike,2023-06-08 19:10:06,2023-06-08 19:13:05,Baldwin at Montgomery,JC020,Astor Place,JC077,40.723499,-74.064335,40.719282,-74.071262,member,June,19:10:06,19:13:05,00:02:59,0.749528,2.983333
4,E205FD8C18BA263A,classic_bike,2023-06-23 18:53:51,2023-06-23 19:17:50,Baldwin at Montgomery,JC020,Adams St & 11 St,HB507,40.723511,-74.064277,40.750916,-74.033541,member,June,18:53:51,19:17:50,00:23:59,4.000179,23.983333
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
409886,A2112D905D1B5FB9,electric_bike,2023-09-05 18:31:42,2023-09-05 18:35:31,8 St & Washington St,HB603,14 St Ferry - 14 St & Shipyard Ln,HB202,40.745984,-74.028199,40.752961,-74.024353,member,September,18:31:42,18:35:31,00:03:49,0.840101,3.816667
409887,2C9D64FF1B8C44C8,classic_bike,2023-09-25 08:36:13,2023-09-25 08:39:13,8 St & Washington St,HB603,14 St Ferry - 14 St & Shipyard Ln,HB202,40.744306,-74.034534,40.752961,-74.024353,member,September,08:36:13,08:39:13,00:03:00,1.289567,3.000000
409888,4F4E24251BBAB45E,classic_bike,2023-09-19 07:55:23,2023-09-19 07:59:00,8 St & Washington St,HB603,14 St Ferry - 14 St & Shipyard Ln,HB202,40.745984,-74.028199,40.752961,-74.024353,member,September,07:55:23,07:59:00,00:03:37,0.840101,3.616667
409889,BB6F0D74150403AC,classic_bike,2023-09-14 07:50:23,2023-09-14 07:52:59,11 St & Washington St,HB502,14 St Ferry - 14 St & Shipyard Ln,HB202,40.749985,-74.027150,40.752961,-74.024353,member,September,07:50:23,07:52:59,00:02:36,0.406219,2.600000
409890,755AE0D4205C0306,classic_bike,2023-09-22 06:52:07,2023-09-22 06:55:49,8 St & Washington St,HB603,14 St Ferry - 14 St & Shipyard Ln,HB202,40.745984,-74.028199,40.752961,-74.024353,member,September,06:52:07,06:55:49,00:03:42,0.840101,3.700000

In [149]:
Bikedata_summer2023.dtypes

ride_id                   object
rideable_type             object
started_at                object
ended_at                  object
start_station_name        object
start_station_id          object
end_station_name          object
end_station_id            object
start_lat                float64
start_lng                float64
end_lat                  float64
end_lng                  float64
member_casual             object
Month                     object
started_time              object
ended_time                object
ride_duration             object
distance                  object
ride_duration_minutes    float64
dtype: object

In [150]:
# Export the DataFrame as a CSV file. 
Bikedata_summer2023.to_csv("output/summer2023-citibike-tripdata.csv", encoding='utf8', index=False)